// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llbeguvpfcdffklaqicf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsYmVndXZwZmNkZmZrbGFxaWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDUzNzcsImV4cCI6MjA2ODUyMTM3N30.-g61YTYFoKH7J3r8faBDAsJmzY4_gZft5kv36fP3U-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});